### ISSUE TITLE
add templating capabilities to Lab definition file

### ISSUE THREAD

**Issue by hellt** [nuagenetworks/nuxctl#9]
complex lab definitions have a lot of duplication in the references: network names, common net octets in addresses, etc

it would be nice to have a `variables` section inside that will be read by the parses and template the rest of the file. For instance:

```yaml
nuxctl_variables:
  pc1_name: pc01
  pc1_ip: 10.0.0.101
  pc2_name: pc02
  pc2_ip: 10.0.0.102

services:
  - name: rdp-{{pc1_name}}
    type: public
    port: 33891
    protocols:
    - tcp
    destination:
      port: 3389
      address: {{pc1_ip}}
  - name: rdp-{{pc2_name}}
    type: public
    port: 33892
    protocols:
    - tcp
    destination:
      port: 3389
      address: {{pc2_ip}}
```
